name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Build application
        run: yarn run build

      - name: Deploy to production (replace with your deployment steps)
        run: |
          npm install -g @nestjs/cli
          nest build
          # Add your deployment commands here
